### ISSUE TITLE
Can not start app daemon

### ISSUE THREAD

**Issue by jingnanzhou** [cosmos/scaffold#46]
Following instruction:
aud init <moniker>
acli keys add validator
aud add-genesis-account validator 100000000stake
aud gentx --name validator
aud collect-gentxs
aud start

The app can not start. The error message is
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4a42ef7]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000132e70, 0x51b4280, 0xc0000cc008, 0x51c6d00, 0xc0000f1000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/github.com/cosmos/cosmos-sdk@v0.38.0/types/module/module.go:265 +0x1d7

**Comment by marbar3778** [comment]
merged the PR, thank you!! 😄
