### ISSUE TITLE
undefined AssetNames and Asset

### ISSUE THREAD

**Issue by mustafasevinc** [cosmos/scaffold#52]
https://github.com/cosmos/scaffold/blob/791139db4ac0f347d2cde219219a8faacc5a4c3e/cmd/utils.go#L34

https://github.com/cosmos/scaffold/blob/791139db4ac0f347d2cde219219a8faacc5a4c3e/cmd/utils.go#L97

go get github.com/cosmos/scaffold/...
# github.com/cosmos/scaffold/cmd
../go/src/github.com/cosmos/scaffold/cmd/utils.go:34:20: undefined: AssetNames
../go/src/github.com/cosmos/scaffold/cmd/utils.go:97:14: undefined: Asset

I'm getting such an error.

**Comment by marbar3778** [comment]
did you run make to first build it?

**Comment by mustafasevinc** [comment]
I upgraded my Golang version. I have done the steps all over again. No more trouble. Thank you.
