### ISSUE TITLE
why naming "acli" "aud" "ascli" "asd"? typo?

### ISSUE THREAD

**Issue by KimuraYu45z** [cosmos/scaffold#55]
How about renaming "appcli" "appd", or using template `{{ .Repo }}cli`, `{{ .Repo }}d`?

**Comment by marbar3778** [comment]
yes we can do this. to use the templating we would need to add a few lines of code to cut the repo names, which should be bad. maybe we just use the first letter?

**Comment by KimuraYu45z** [comment]
Oh I see.
I think appcli appd is better than {first letter}cli {first letter}d.

**Comment by okwme** [comment]
closed by #63
