### ISSUE TITLE
go run  cmd/aud/main.go ->undefined error

### ISSUE THREAD

**Issue by hschoenburg** [cosmos/scaffold#60]
steps to reproduce
```bash
$  scaffold app lvl-1 hschoenburg test-app
$ cd test-app
$ go run cmd/aud/main.go
cmd/aud/main.go:60:21: undefined: AddGenesisAccountCmd
```

`go run cmd/acli/main.go` works no problem

**Comment by marbar3778** [comment]
odd, the needed function is there: https://github.com/cosmos/scaffold/blob/master/templates/lvl-1/cmd/aud/genaccounts.go.tmpl

could you try make install then the same cmd again?

**Comment by hschoenburg** [comment]
ah turns out you have to supply each file as individual args to `go run` so
`$ go run cmd/aud/main.go  cmd/aud/genaccounts.go s\tart` worked just fine
