### ISSUE TITLE
“CONSENSUS FAILURE!!!“ issue after restarting node

### ISSUE THREAD

**Issue by xoren93** [cosmos/scaffold#71]
After creating a new app on Scaffold and starting the node using  `appd start`  command everything works well, however, when we stop the node using ctrl+c and try to restart it again it stops working and shows the following error message “CONSENSUS FAILURE!!!“.

![image](https://user-images.githubusercontent.com/5453219/78368548-d7aa4c00-75d4-11ea-9d14-99dc5aaf645b.png)

**Comment by marbar3778** [comment]
this was due to a bug in 0.38.0 for short-lived chains, if you bump to 0.38.1 this will go away.

**Comment by xoren93** [comment]
Thank you very much for your quick reply, after updating cosmos-sdk library the problem was resolved.
