### ISSUE TITLE
cannot install scaffold, probably because of go-bindata

### ISSUE THREAD

**Issue by anhdungle93** [cosmos/scaffold#79]
When I tried to install scaffold by `make` at first I get the following error 
```
(base) ➜  scaffold git:(master) ✗ make
go: found github.com/go-bindata/go-bindata/... in github.com/go-bindata/go-bindata v3.1.2+incompatible
/bin/sh: go-bindata: command not found
make: *** [generate] Error 127
```
Then I installed go-bindata 3.19.0 with `brew install go-bindata` and run the command `make` again. All I got was

```
(base) ➜  scaffold git:(master) ✗ make
go: found github.com/go-bindata/go-bindata/... in github.com/go-bindata/go-bindata v3.1.2+incompatible
```

**Comment by marbar3778** [comment]
in the second go when you ran `scaffold` did anything show up? i just removed go-bindata and scaffold and ran make, got the same output as you and scaffold was installed

**Comment by anhdungle93** [comment]
@marbar3778  I just get the `zsh: command not found: scaffold` even after restarting the terminal.

**Comment by dmitryermichev** [comment]
@anhdungle93  
I had the same issue. Check first that you path contains $GOPATH/bin. In my case that was error cause. If you use zsh you can add export to ~/.zshrc
`export PATH=$HOME/bin:/usr/local/bin:$HOME/go/bin:$PATH`

**Comment by anhdungle93** [comment]
@dmitryermichev thank you very much, this is indeed the issue. Both `go-bindada` and `scaffold` but not accessible in `$PATH`.
